spring.datasource.url=jdbc:postgresql://localhost:5432/skladDb
spring.datasource.username = postgres
spring.datasource.password = ZSsazava12

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true